### ISSUE TITLE
Connection to Etatherm control unit does not reestablish on network failure

### ISSUE THREAD

**Issue by mbisak** [mbisak/etatherm-ha-bridge#5]
Traceback (most recent call last):
  File "C:\etatherm\etatherm\etatherm.py", line 166, in etathermSendFrame
    self.etathermSession.send(reqFrame)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\logging\__init__.py", line 1150, in emit
    msg = self.format(record)
  File "C:\Program Files\Python\Python313\Lib\logging\__init__.py", line 998, in format
    return fmt.format(record)
           ~~~~~~~~~~^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\logging\__init__.py", line 711, in format
    record.message = record.getMessage()
                     ~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\logging\__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\etatherm\mqtt.py", line 33, in <module>
    etherm.processCmdQueue()
  File "C:\etatherm\etatherm\etatherm.py", line 1378, in processCmdQueue
    self.updateAddressParameters()
  File "C:\etatherm\etatherm\etatherm.py", line 1854, in updateAddressParameters
    self.setGOCPresetParameters(self.retrieveGOCParameters())
  File "C:\etatherm\etatherm\etatherm.py", line 541, in retrieveGOCParameters
    respFrame = self.etathermSendFrame(reqFrame)
  File "C:\etatherm\etatherm\etatherm.py", line 172, in etathermSendFrame
    logging.error("Socket error on send, resending frame", reqFrame.hex())
Message: 'Socket error on send, resending frame'
Arguments: ('1001ff0110f078028b75ffff',)

**Comment by mbisak** [comment]
Bug
